# Actors.
vendor: "Vendor\n(primary)" {shape: person}
admin: "Company admin\n(secondary)" {shape: person}
agent: "Endpoint agent\n(secondary)" {shape: person}

# External events.
problem_detected: "Problem detected"
culprit_found: "Culprit found"
execute: "Execute new code deployment"

# Blockchain & blockchain events.
blockchain: "Blockchain" {
  search_deployments: "Search deployments"
  listen: "Connect & listen"
  new_deployment: "New deployment"
  download_deployment: "Download deployment"
  deploy: "Attempt deployment"
  verify_deployment: "Verify deployment"
  publish_deployment: "Publish deployment"
}

# Connections.
admin -- problem_detected
agent -- blockchain.listen

problem_detected -> blockchain.search_deployments: "<<include>>" {
  style: {
    stroke-dash: 5
  }
}

blockchain.search_deployments -> culprit_found: "<<include>>" {
  style: {
    stroke-dash: 5
  }
}

blockchain.listen -> blockchain.new_deployment -> blockchain.download_deployment -> execute: "<<include>>" {
  style: {
    stroke-dash: 5
  }
}

vendor -- blockchain.deploy -> blockchain.verify_deployment -> blockchain.publish_deployment: "<<include>>" {
  style: {
    stroke-dash: 5
  }
}
